### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/clocky-countdown#7]
Hi @eduardorasgado, do you need a logo for this project too? It will be a pleasure for me to work again with you. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by eduardorasgado** [comment]
Go ahead bro! See the project use on: https://clocky-countdown.herokuapp.com/ Get inspire in some logo for this countdown utility for developers!

**Comment by zuurw** [comment]
Hi @eduardorasgado, here is my design for clocky (the name it´s amazing), so for the concept of this logo I put together two things, which was an image of developers and an image of a time count, as you can see below.
Looking at the logo you can see my inspiration, the logo has a cogwheel as a reference to developers and another half with a points indicating the time points of a clock, the circle with a point in the middle, represents the pointer of the seconds on the move.

I hope you like this design and my explanation, if you do not like it I can make another design.

![proposal](https://user-images.githubusercontent.com/40801473/43650903-e0a788da-9738-11e8-86f3-a3cb930b50d0.png)

**Comment by eduardorasgado** [comment]
Good bro. I like the purple, the one in the middle, looks good, send me a pull request to the README.md, cheers @zuurw , thanks mate.
